// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpXGjFy2UkLCLX1BG1tb2u-GMP_AHdvNo',
    appId: '1:161844389683:web:95442a7a2c12ba6a138046',
    messagingSenderId: '161844389683',
    projectId: 'chat-21-c5381',
    authDomain: 'chat-21-c5381.firebaseapp.com',
    storageBucket: 'chat-21-c5381.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASf5oweIqX9Qc4SVnLqXX1Mn2vX7QyqKg',
    appId: '1:161844389683:android:d962055a4905be99138046',
    messagingSenderId: '161844389683',
    projectId: 'chat-21-c5381',
    storageBucket: 'chat-21-c5381.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU7JUhmVUUs_8NbW8NJOrWEstFsRjZImc',
    appId: '1:161844389683:ios:e4ba6cf944d87ab3138046',
    messagingSenderId: '161844389683',
    projectId: 'chat-21-c5381',
    storageBucket: 'chat-21-c5381.firebasestorage.app',
    iosBundleId: 'com.example.chat21',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU7JUhmVUUs_8NbW8NJOrWEstFsRjZImc',
    appId: '1:161844389683:ios:e4ba6cf944d87ab3138046',
    messagingSenderId: '161844389683',
    projectId: 'chat-21-c5381',
    storageBucket: 'chat-21-c5381.firebasestorage.app',
    iosBundleId: 'com.example.chat21',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpXGjFy2UkLCLX1BG1tb2u-GMP_AHdvNo',
    appId: '1:161844389683:web:3ef5b627e4e3ec8c138046',
    messagingSenderId: '161844389683',
    projectId: 'chat-21-c5381',
    authDomain: 'chat-21-c5381.firebaseapp.com',
    storageBucket: 'chat-21-c5381.firebasestorage.app',
  );

}